### ISSUE TITLE
"list index out of range" error on debian 11

### ISSUE THREAD

**Issue by geotekberlin** [SnejPro/check_synology#8]
Hi,
I can't get this plugin to work on Debian 11 with python 3,9, no matter what parameters are given. Example:

```
root@geotek-icinga:~# /usr/lib/nagios/plugins/check_synology.py -v 2c -H 192.168.146.35 -C xxxxx
Traceback (most recent call last):
  File "/usr/lib/nagios/plugins/check_synology.py", line 467, in <module>
    res = snmpget(queue)
  File "/usr/lib/nagios/plugins/check_synology.py", line 219, in snmpget
    snmpres = proc_snmpget(oids)
  File "/usr/lib/nagios/plugins/check_synology.py", line 137, in proc_snmpget
    return proc(command, oids)
  File "/usr/lib/nagios/plugins/check_synology.py", line 122, in proc
    key=re.findall("(iso(\.[0-9]+)+) ", l)[0][0]
IndexError: list index out of range
```

Tested with different Synology Models. Other Synology plugins return valid results. Any idea what is causing this?

**Comment by SnejPro** [comment]
Hi,

have you installed snmp?

`apt install snmp`

Greetings

Jens

**Comment by geotekberlin** [comment]
SNMP is installed and working on the Icinga side and all NAS devices. Even the Synology devices respond to other check modules correclty, only this plugin doesn't work.

**Comment by okrouhly** [comment]
Your snmp utilities probably returns "1" instead of "iso" that is searched for at line 122. I think my currently created branch could fix it. I have added option -n to snmp commands so it always return 1 instead of iso (thus modified the finall... in my brach).

**Comment by geotekberlin** [comment]
Hi, would you mind sharing your code so that I can see it if fixes my issue?

**Comment by SnejPro** [comment]
@geotekberlin Please try it again. I've added -n to the snmp commands

**Comment by geotekberlin** [comment]
Great, this modification did indeed fix the "index out of range" error. All test seem to work now except for "storage" which returns the following error:
```
Traceback (most recent call last):
  File "/usr/lib/nagios/plugins/check_synology.py", line 521, in <module>
    render_storage(queue)
  File "/usr/lib/nagios/plugins/check_synology.py", line 415, in render_storage
    size_bytes = int(r['1.3.6.1.2.1.25.2.3.1.4.'+id]['value'])*int(r['1.3.6.1.2.1.25.2.3.1.5.'+id]['value'])
ValueError: invalid literal for int() with base 10: '4096 Bytes'
```

and "memory" which returns:

```
Traceback (most recent call last):
  File "/usr/lib/nagios/plugins/check_synology.py", line 480, in <module>
    v["value"] = int(v["value"])*1024
ValueError: invalid literal for int() with base 10: '5914992 kB'
```

**Comment by okrouhly** [comment]
Hi
You can try my branch that removes the Units of Measure returned by storage and memory queries...
https://github.com/okrouhly/check_synology/blob/xc-python3.6/check_synology.py

Jan

**Comment by geotekberlin** [comment]
Hi Jan, thanks for this tip, the binary from your branch solves the storage and memory errors!

**Comment by geotekberlin** [comment]
Hello SnejPro, my I suggest to include okrouhlys fix into your branch? ´His binaries work for us while your's don't.

**Comment by SnejPro** [comment]
> Hello SnejPro, my I suggest to include okrouhlys fix into your branch? ´His binaries work for us while your's don't.

Same answer as in https://github.com/SnejPro/check_synology/issues/11#issuecomment-1076469337

**Comment by SnejPro** [comment]
Is the error still there?

**Comment by SnejPro** [comment]
Fixed in PR https://github.com/SnejPro/check_synology/pull/17
